### ISSUE TITLE
Execute registered commands from code

### ISSUE THREAD

**Issue by primus192** [jbtronics/ESP32Console#10]
Hello. I am currently moving my project from my "quasi" console that i had implemented while ago.
I wonder if it is somehow possible to execute registered commands from inside like console.runCommand("mode 5")
or simpler console.println("mode 5") which will act as if i were inputting this command directly to console. How can i achieve execution of the command  using Your implementation of the console?
The intention for using that is for example i want to execute commands remotely via bluetooth low energy and i have function and its arguments passed by String so i need to execute it from the "inside".

**Comment by jbtronics** [comment]
The underlying console command of the ESP-IDF offers a command for that [`esp_console_run()`](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/console.html#_CPPv415esp_console_runPKcPi).

That is basically what this library calls internally. What this function does not offer is the command interpolation feature using "environment variables" (as this is done by the ESP32Console library itself).

And you should note that the executed command outputs to the configured stdout, so if the command prints something, you will not be able to catch it programmatically (or at least not easy)

**Comment by primus192** [comment]
Thank you, i did my own function based on the while(1) loop that i found in the repl task function. I ommited everything about linenoise just straight esp_console_run() with returning errors and it is working flawlessly. I do not need interpolation for now so it is okay for me.

I have one more question about statement that the one can not use Serial.print() after initializing console. Using Serial.println() is working for me. Is it intentional or am I missing something?
