### ISSUE TITLE
Difficulty using editor in MacOS

### ISSUE THREAD

**Issue by thomaswardiii** [jbtronics/ESP32Console#13]
When connecting my ESP32 to my MacBook, I tend to use `screen` to connect to the serial port for access to the ESP32Console command line.

I am having major difficulties in using the edit command, as it does not seem to redraw the UI properly. I'm hoping to either find out what settings to adjust in `screen`, such as terminal type, or a better, preferably free, solution to use ESP32Console's edit command on MacOS

**Comment by jbtronics** [comment]
I guess that either the kilo editor has problems to detect the capabilities of the terminal emulator (in that case screen) or that screen for some reason does not interpret the VT100 codes correctly. I guess that should be somehow fixable with the right termcap configuration for screen.

However if not many experiences with screen and absolutely none with MacOS
