### ISSUE TITLE
Library does not work on ESP32S3

### ISSUE THREAD

**Issue by pieterjm** [jbtronics/ESP32Console#7]
The library appears not to work on an ESP32 S3 (LILYGO ESP32 S3). The example basic.ino sketch compiles without a problem. Output from the ESP is received in the terminal, but no prompt is visible or commands can be sent.

**Comment by pieterjm** [comment]
Never mind. Appears to be a problem with my MCU

**Comment by mgrouch** [comment]
How did you solve it? I have same issue with
m5stack atomS3 with esp32-S3?

thanks
