### ISSUE TITLE
use UART2 on wemos lolin D32 pro

### ISSUE THREAD

**Issue by marcelinDelcour** [jbtronics/ESP32Console#9]
Hi Jan,

any chance we can use your lib with another UART ? i've tried playing with console.begin

//void Console::begin(int baud, int rxPin, int txPin, uint8_t channel)
console.begin(115200, RX2, TX2, 0);

but it's not working so far. At best, the console answer on uart0 via USB cable. Or my board reboot every 1 s when I'm change channel to anything else than 0

I saw that rxPin or txPin are not use in begin(...) function. So I wonder if it's possible to use another UART

**Comment by jbtronics** [comment]
You are right, the txPin and rxPin option were never used (and actually there were another bug which prevented the use of another UART channel).

With Version 1.2.1 you should be able to configure the rxPin and txPin properly and even using other UART channels, which allows you to use ESP32Console parallel to Serial.println on its own UART channel (see `other_uart_channel` example).
